ALTER TYPE "SyncRunStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE "IntegrationJobStatus" ADD VALUE IF NOT EXISTS 'CANCEL_REQUESTED';
ALTER TYPE "IntegrationJobStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
